server:
  port: 18080
  servlet:
    context-path: /v
spring:
  mail:
    host: smtp.163.com
    username: XXXXXX
    # 163邮箱授权码
    password: XXXXXX
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
